const RECEIVED_PICTURE = "RECEIVED_PICTURE";
const FETCH_ERROR = "FETCH_ERROR";
const MORE_RECEIVED_PICTURE = "MORE_RECEIVED_PICTURE";
const SET_LOADING = "SET_LOADING";

export { RECEIVED_PICTURE, FETCH_ERROR, MORE_RECEIVED_PICTURE, SET_LOADING };
